<?php namespace ProcessWire;
/**
 * MarkupPwpswpGalleryFlex
 * 
 * Example gallery: Uses flexbox.
 * legacy plain theme
 * 
 */
class MarkupPwpswpGalleryFlex extends MarkupPwpswpGallery implements Module {

    public static function getModuleInfo() {
        return array(
            'title' => 'Pwpswp Gallery: Flex',
            'author' => 'Steffen Henschel',
            'version' => '0.0.1',
            'summary' => __('Example gallery: Uses flexbox. Alias: "flex"'),
            
            'permission' => [],
            'autoload' => false,
            'singular' => false,
            'permanent' => false,
            'requires' => [
                'ProcessWire>=3.0.0',
                'PHP>=5.6',
                'MarkupPwpswpGallery'
            ],
            'installs' => []
        );
    }

    /**
     * alias
     * 
     * return a short unique name for this module here
     * legacy theme name
     * it will be used for css classes, etc.
     * 
     * @return string
     */
    static public function alias() {
        return 'flex';
    }
}
    